// Generated by scripts/generate-umbrella-exports.ts — do not edit.
export * from '@c15t/vue/runtime/components/consent-legal-links.vue';
export { default } from '@c15t/vue/runtime/components/consent-legal-links.vue';
