// Generated by scripts/generate-umbrella-exports.ts — do not edit.
export * from '@c15t/vue/runtime/components/iab-stack-item.vue';
export { default } from '@c15t/vue/runtime/components/iab-stack-item.vue';
