// Generated by scripts/generate-umbrella-exports.ts — do not edit.
export * from '@c15t/vue/runtime/components/trigger-icon.vue';
export { default } from '@c15t/vue/runtime/components/trigger-icon.vue';
