// Generated by scripts/generate-umbrella-exports.ts — do not edit.
export * from '@c15t/vue/runtime/server/route-prefix.nuxt.js';
export { default } from '@c15t/vue/runtime/server/route-prefix.nuxt.js';
