// Generated by scripts/generate-umbrella-exports.ts — do not edit.
export * from '@c15t/vue/runtime/primitives/tabs/tabs-trigger.vue';
export { default } from '@c15t/vue/runtime/primitives/tabs/tabs-trigger.vue';
