/** @generated by scripts/subs/scan-icons.ts — do not edit manually */

export const OPTIN_ICONS = [
	'alert',
	'chevron-down',
	'close',
	'external-link',
	'eye',
	'minus',
	'radio-button',
	'refresh',
] as const;

export type UsedIconName = (typeof OPTIN_ICONS)[number];
export const OPTIN_ICON_SET = new Set<string>(OPTIN_ICONS as readonly string[]);
export const isUsedIconName = (name: string): name is UsedIconName =>
	OPTIN_ICON_SET.has(name);
