<script>
// Generated by scripts/generate-umbrella-exports.ts — do not edit.
import Component from '@c15t/vue/runtime/primitives/preference-item/preference-item-trigger.vue';
export default Component;
</script>
