// Generated by scripts/generate-umbrella-exports.ts — do not edit.
export * from '@c15t/vue/runtime/primitives/preference-item/preference-item-header.vue';
export { default } from '@c15t/vue/runtime/primitives/preference-item/preference-item-header.vue';
