/**
 * Persistence's write half: storing records after kernel events and
 * reconciling with other runtimes. Loaded on demand by `../index.ts`, which
 * keeps hydration (the read the first banner needs), the event listeners
 * and clearing storage in the first load.
 *
 * Everything here imports only from this directory. First-load functions
 * arrive as {@link PersistenceTools}, so bundlers load this as one chunk
 * instead of splitting the modules it shares with the first load into
 * chunks of their own.
 *
 * The ordering rules (per-category merge, ties, subjects, the clear epoch)
 * are in `reconcile.ts`; the write-before-send timing in `schedule.ts`.
 *
 * @internal
 */
import type {
	CategoryDecision,
	ConsentSubject,
	ExplicitChoice,
} from '../../../consent-record/types';
import type { ConsentSnapshot, HydrationRecords } from '../../../types';
import type { StoredRecords } from '../hydrate';
import type { StoredIabMetadata } from '../record-codec';
import {
	choiceToWrite,
	fingerprintStoredRecords,
	mayWriteNotice,
	mayWriteVendorChoice,
	sameRecord,
	selectReconciledRecords,
	subjectToWrite,
} from './reconcile';
import type { StorageFingerprints, StoredRecordKind } from './reconcile';
import { createWriteScheduler } from './schedule';
import { createRecordStore } from './store';
import type {
	PersistenceContext,
	PersistenceTools,
	PersistenceWriter,
	WriteKind,
} from './types';
import {
	writeChoiceToStorage,
	writeNoticeToStorage,
	writeVendorChoiceToStorage,
} from './write';

/**
 * Create the write half of one persistence handle.
 *
 * @param context - The handle's kernel, storage, clock and event state.
 * @param tools - First-load functions the writer calls.
 * @returns The writer. It writes nothing until asked.
 */
export const createPersistenceWriter = function createPersistenceWriter(
	{ kernel, now, state, storageConfig }: PersistenceContext,
	tools: PersistenceTools
): PersistenceWriter {
	const store = createRecordStore(tools);

	// IAB transport metadata carried by the stored record. Preserved on the
	// next explicit save so an envelope rewrite never drops it.
	let storedIab: StoredIabMetadata | null = null;

	// What storage held when this runtime last read or wrote each record.
	// Reconciliation acts only on records that changed since.
	let seen: StorageFingerprints = {};
	// Records this runtime wrote with parts taken from storage that memory
	// does not hold yet. The next reconciliation treats them as changed.
	const unadopted = new Set<StoredRecordKind>();
	// Category decisions this runtime has stored. Another
	// tab can read storage before one of these writes lands and then write
	// over it; reconciliation writes back any it finds missing.
	const ownDecisions = new Map<
		string,
		{ decision: CategoryDecision; epoch: number }
	>();
	// The subject id storage held at the last readable read or write. An
	// in-memory id equal to it, or to the id a save generated because this
	// runtime held none (`state.freshSubjectId`), yields to a stored
	// subject; any other one came from the server and is kept.
	let seenSubjectId: string | null | undefined;
	// The clear epoch the records in memory belong to. A stored epoch past
	// it means another runtime cleared the records since.
	let memoryEpoch = 0;

	const rememberSubject = function rememberSubject(
		records: HydrationRecords
	): void {
		if (records.choice !== undefined) {
			seenSubjectId = records.subject?.subjectId ?? null;
		}
	};

	const subjectYields = function subjectYields(): boolean {
		const id = kernel.getSnapshot().subject?.subjectId;
		return !id || id === state.freshSubjectId || id === seenSubjectId;
	};

	const observe = function observe(kind?: StoredRecordKind): void {
		if (typeof document === 'undefined') {
			return;
		}
		const read = tools.read(storageConfig, now());
		const prints = fingerprintStoredRecords(read);
		if (kind) {
			seen[kind] = prints[kind];
		} else {
			seen = prints;
		}
		if (kind === undefined || kind === 'choice') {
			rememberSubject(read.records);
		}
		if (kind === undefined) {
			memoryEpoch = read.epoch;
		}
	};

	/**
	 * Whether the subject in memory was generated by a save made after
	 * `epoch`. Such a subject belongs to the post-clear history even when
	 * this runtime missed the clear, so it is kept.
	 */
	const subjectBornAfter = function subjectBornAfter(epoch: number): boolean {
		const id = kernel.getSnapshot().subject?.subjectId;
		return (
			id !== undefined &&
			id === state.freshSubjectId &&
			state.freshSubjectAt !== undefined &&
			state.freshSubjectAt > epoch
		);
	};

	/**
	 * Whether storage holds something for a record that memory lacks: another
	 * runtime changed it since this runtime last saw it, or this runtime's
	 * own merged write took parts of it from storage. Such a record wins a
	 * tie with a queued write and blocks a subject-only rewrite.
	 */
	const changedSinceSeen = function changedSinceSeen(
		kind: StoredRecordKind,
		read: StoredRecords
	): boolean {
		const print = fingerprintStoredRecords(read)[kind];
		return (print !== undefined && print !== seen[kind]) || unadopted.has(kind);
	};

	/**
	 * Mark a record after writing it. The record is seen as written, so a
	 * later removal is recognised as one. A write that took anything from
	 * storage is also marked unadopted: memory lacks part of it, so the next
	 * reconciliation treats it as changed and brings the merge into memory.
	 */
	const markWritten = function markWritten(
		kind: StoredRecordKind,
		wroteOwnState: boolean
	): void {
		observe(kind);
		if (wroteOwnState) {
			unadopted.delete(kind);
		} else {
			unadopted.add(kind);
		}
	};

	/**
	 * The subject a write stores. After a clear this runtime missed, a
	 * subject from before it belongs to the cleared history: only what
	 * storage holds now is kept, or none. A subject a save generated after
	 * the clear follows the usual rules.
	 */
	const writtenSubject = function writtenSubject(
		snapshot: ConsentSnapshot,
		stored: ConsentSubject | null | undefined,
		subjectOnly: boolean,
		read: StoredRecords
	): ConsentSubject | null {
		if (subjectOnly) {
			return snapshot.subject;
		}
		if (read.epoch > memoryEpoch && !subjectBornAfter(read.epoch)) {
			return stored ?? null;
		}
		return subjectToWrite(snapshot.subject, stored, subjectYields());
	};

	// Every write reads storage first and voids what this runtime holds from
	// before the stored clear epoch, so a runtime that missed a clear can
	// only write decisions made after it.
	const choiceWrites = createWriteScheduler(() => {
		const subjectOnly = !state.choiceRecorded;
		state.choiceRecorded = false;
		const snapshot = kernel.getSnapshot();
		const at = now();
		const read = tools.read(storageConfig, at);
		const clearMissed = read.epoch > memoryEpoch;
		const stored = read.records.choice ?? null;
		const explicitChoice =
			subjectOnly && clearMissed
				? null
				: choiceToWrite(
						tools.choiceSince(
							snapshot.explicitChoice,
							read.epoch,
							!clearMissed
						),
						stored,
						subjectOnly,
						changedSinceSeen('choice', read),
						tools.merge
					);
		if (!explicitChoice) {
			return;
		}
		const subject = writtenSubject(
			snapshot,
			stored ? read.records.subject : null,
			subjectOnly,
			read
		);
		writeChoiceToStorage(
			store,
			{ ...snapshot, explicitChoice, subject },
			storedIab,
			storageConfig,
			at,
			read.epoch
		);
		// Only what was written counts as this runtime's: the merge keeps a
		// newer stored decision over the one in memory, and that older
		// in-memory value must never be written back later.
		for (const [category, decision] of Object.entries(
			explicitChoice.categories
		)) {
			if (decision) {
				ownDecisions.set(category, { decision, epoch: read.epoch });
			}
		}
		markWritten(
			'choice',
			sameRecord(explicitChoice, snapshot.explicitChoice) &&
				sameRecord(subject, snapshot.subject)
		);
	});
	const noticeWrites = createWriteScheduler(() => {
		const snapshot = kernel.getSnapshot();
		const at = now();
		const read = tools.read(storageConfig, at);
		const ours = tools.noticeSince(snapshot.noticeDismissal, read.epoch);
		if (
			ours &&
			mayWriteNotice(
				ours,
				read.records.noticeDismissal ?? null,
				changedSinceSeen('notice', read)
			)
		) {
			writeNoticeToStorage(store, snapshot, storageConfig, at);
			observe('notice');
		}
	});
	const vendorWrites = createWriteScheduler(() => {
		const subjectOnly = !state.vendorsRecorded;
		state.vendorsRecorded = false;
		const snapshot = kernel.getSnapshot();
		const at = now();
		const read = tools.read(storageConfig, at);
		const clearMissed = read.epoch > memoryEpoch;
		const ours = tools.vendorsSince(snapshot.vendorChoice, read.epoch);
		if (
			(snapshot.vendorChoice && !ours) ||
			(subjectOnly && clearMissed) ||
			!mayWriteVendorChoice(
				ours,
				read.records.vendorChoice ?? null,
				subjectOnly,
				changedSinceSeen('vendors', read)
			)
		) {
			return;
		}
		const subject = writtenSubject(
			snapshot,
			read.vendorSubject,
			subjectOnly,
			read
		);
		writeVendorChoiceToStorage(
			store,
			{ ...snapshot, subject },
			storageConfig,
			at
		);
		markWritten('vendors', sameRecord(subject, snapshot.subject));
	});
	const writes = {
		choice: choiceWrites,
		notice: noticeWrites,
		vendors: vendorWrites,
	} satisfies Record<WriteKind, unknown>;

	const flush = function flush(): void {
		choiceWrites.flush();
		noticeWrites.flush();
		vendorWrites.flush();
	};

	/**
	 * Schedule the writes that restore what this runtime stored and another
	 * runtime then wrote over. localStorage has no compare-and-swap, so two
	 * tabs can both read before either writes and the second write drops the
	 * first tab's category. A decision is written back only when this runtime
	 * stored it, still holds it, and storage holds nothing as new for that
	 * category. Nothing the clear epoch voids or another runtime replaced
	 * comes back, and once storage holds the merge no tab writes again.
	 */
	const restoreLostWrites = function restoreLostWrites(
		read: StoredRecords
	): void {
		const snapshot = kernel.getSnapshot();
		const storedChoice = read.records.choice;
		if (storedChoice === undefined) {
			return;
		}
		const lost = [...ownDecisions].some(([category, written]) => {
			const { decision: own } = written;
			const key = category as keyof ExplicitChoice['categories'];
			const held = snapshot.explicitChoice?.categories[key];
			const stored = storedChoice?.categories[key];
			return (
				held !== undefined &&
				held.confirmedAt === own.confirmedAt &&
				held.value === own.value &&
				// A decision in the clearing millisecond counts when it was
				// written under that epoch, as in `choiceSinceEpoch`.
				(own.confirmedAt > read.epoch ||
					(own.confirmedAt === read.epoch && written.epoch === read.epoch)) &&
				(!stored || stored.confirmedAt < own.confirmedAt)
			);
		});
		if (lost) {
			state.choiceRecorded = true;
			choiceWrites.schedule();
		}
	};

	const reconcile = function reconcile(): boolean {
		// oxlint-disable-next-line no-use-before-define -- Mutually recursive with the scheduler.
		scheduledReconcile.cancel();
		if (typeof document === 'undefined') {
			return false;
		}
		// Land this runtime's queued writes first. Each one merges with what
		// storage holds, so it cannot undo a newer decision another runtime
		// stored meanwhile.
		flush();
		const at = now();
		const stored = tools.read(storageConfig, at);
		const next = selectReconciledRecords(
			kernel.getSnapshot(),
			stored,
			seen,
			at,
			subjectYields(),
			unadopted,
			memoryEpoch,
			subjectBornAfter(stored.epoch),
			tools
		);
		({ seen } = next);
		unadopted.clear();
		rememberSubject(stored.records);
		memoryEpoch = stored.epoch;
		const { records } = next;
		if (!records) {
			restoreLostWrites(stored);
			return false;
		}
		const result = kernel.hydrate(records);
		if (result.ok === false) {
			console.warn(
				'[c15t] Stored consent records were rejected.',
				result.issues
			);
			return false;
		}
		if (records.choice !== undefined) {
			storedIab = records.choice ? stored.iab : null;
		}
		restoreLostWrites(stored);
		return result.changed;
	};

	// Coalesces bursts of triggers (one save writes several keys) into one
	// read in a later macrotask.
	const scheduledReconcile = createWriteScheduler(reconcile);

	return {
		adopt(read, iab) {
			seen = fingerprintStoredRecords(read);
			rememberSubject(read.records);
			memoryEpoch = read.epoch;
			if (iab && read.records.choice !== undefined) {
				storedIab = read.iab;
			}
		},
		clearStorage(at) {
			// Writes queued before the clear belong to the cleared records.
			// The caller already reset what the kernel's events recorded, and
			// anything recorded since is after the clear.
			choiceWrites.cancel();
			noticeWrites.cancel();
			vendorWrites.cancel();
			unadopted.clear();
			ownDecisions.clear();
			storedIab = null;
			tools.clear(storageConfig, at, memoryEpoch);
			observe();
		},
		dispose() {
			scheduledReconcile.cancel();
		},
		flush,
		reconcile,
		schedule(kind) {
			writes[kind].schedule();
		},
		scheduleReconcile: scheduledReconcile.schedule,
	};
};
