name: "✨ Feature Request"
description: Suggest a new feature for c15t.com
labels: ["Feature", "Needs Approval"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out this form as completely as possible.
        
        Before submitting:
        1. Search [existing requests](https://github.com/c15t/c15t/issues)
        2. Read the [documentation](https://c15t.com/docs)
        3. Join our [Discord](https://c15t.com/discord) for discussions

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature are you suggesting?
      options:
        - "🚀 New Capability"
        - "🔧 Enhancement"
        - "🎨 UI/UX Improvement"
        - "⚡ Performance"
        - "🔒 Security"
        - "🧰 Developer Experience"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I'm trying to accomplish X, but..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        Describe your ideal solution. Be specific!
        - What would it look like?
        - How would it work?
        - What are the key benefits?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What alternatives have you considered?
      placeholder: "I've tried..."
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Add any other context:
        - Screenshots/mockups
        - Similar features in other tools
        - Use cases
        - Implementation ideas
    validations:
      required: false