name: "⚡ Performance Issue"
description: Report a performance problem or bottleneck
labels: ["Performance", "Needs Approval"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a performance issue! Please provide as much data as possible to help us investigate.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of c15t.com are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: textarea
    id: benchmark
    attributes:
      label: Performance Data
      description: |
        Please provide any relevant performance metrics:
        - Response times
        - Memory usage
        - CPU usage
        - Load testing results
      placeholder: |
        Before: 200ms response time
        After: 2000ms response time
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How can we reproduce this performance issue?
      placeholder: |
        1. Setup environment with X data
        2. Run operation Y
        3. Measure using tool Z
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment:
        - Hardware specs
        - OS version
        - Node.js version
        - Database version
        - Load conditions
    validations:
      required: true 