export { type Branding, brandingSchema, brandingValues } from './branding';
export {
	buildConsentManifestFromConfig,
	type ConsentManifest,
	type ConsentManifestBranding,
	type ConsentManifestConfig,
	type ConsentManifestDefaults,
	type ConsentManifestGVLReference,
	type ConsentManifestIAB,
	type ConsentManifestPolicyFailure,
	type ConsentManifestPolicyPack,
	type ConsentManifestTranslationInputs,
	checkJurisdiction,
	createConsentManifestPolicyPack,
	type ResolveInitFromManifestInputs,
	type ResolveInitFromManifestOptions,
	resolveInitFromManifest,
	resolvePolicyResolutionFromManifest,
	sliceConsentManifestLanguage,
} from './consent-manifest';
// Export constants separately for runtime-safe usage
export {
	brandingValues as brandingValuesConst,
	jurisdictionCodes as jurisdictionCodesConst,
} from './constants';
export {
	buildConsentId,
	type ConsentSubmissionIdentity,
	type EntityKind,
	generateDeterministicId,
	generateEntityId,
} from './entity-id';
export {
	CONSENT_REQUEST_HEADER_NAMES,
	COUNTRY_HEADERS,
	type ConsentRequestHeaderInputs,
	consentInputsToOverrides,
	extractConsentRequestInputs,
	getRegionFromHeaders,
	headersToRecord,
	parseGlobalPrivacyControl,
	REGION_HEADERS,
} from './geo-headers';
export {
	type GlobalVendorList,
	type GVLDataCategory,
	type GVLFeature,
	type GVLPurpose,
	type GVLSpecialFeature,
	type GVLSpecialPurpose,
	type GVLStack,
	type GVLVendor,
	type GVLVendorUrl,
	globalVendorListSchema,
	gvlDataCategorySchema,
	gvlFeatureSchema,
	gvlPurposeSchema,
	gvlSpecialFeatureSchema,
	gvlSpecialPurposeSchema,
	gvlStackSchema,
	gvlVendorSchema,
	gvlVendorUrlSchema,
} from './gvl';
export {
	type JurisdictionCode,
	jurisdictionCodeSchema,
	jurisdictionCodes,
} from './jurisdiction';
export {
	type NonIABVendor,
	type NonIABVendorConsent,
	nonIABVendorConsentSchema,
	nonIABVendorSchema,
} from './non-iab-vendor';
export {
	createDeterministicFingerprint,
	createDeterministicFingerprintSync,
	createMaterialPolicyFingerprint,
	createMaterialPolicyFingerprintSync,
	hashSha256Hex,
	stableStringify,
} from './policy-fingerprint';
export {
	matchPolicyRules,
	POLICY_CONTRACT_HEADER,
	POLICY_CONTRACT_VERSION,
	type PolicyMatchEntry,
	type PolicyMatchOutcome,
	type PolicyResolution,
	type PolicyResolutionFailed,
	type PolicyResolutionFailure,
	type PolicyResolutionMatched,
	type PolicyResolutionNoMatch,
	type PolicyResolutionUnconfigured,
	type PolicyResolutionWire,
	parsePolicyContractHeader,
	readPolicyResolutionWire,
	resolvePolicyRules,
	SAFE_FALLBACK_POLICY_FINGERPRINTS,
	SAFE_FALLBACK_POLICY_ID,
	type SafeFallbackPolicyInput,
	safeFallbackPolicyInput,
	safeFallbackPolicyRule,
	writePolicyResolutionWire,
} from './policy-resolution';
export {
	canonicalizePolicySet,
	collectResolvedPolicyRuleIssues,
	DEFAULT_CHOICE_VALIDITY_DAYS,
	DEFAULT_NOTICE_VALIDITY_DAYS,
	expectedPolicyActions,
	inspectPolicyRules,
	isPlainPolicyObject,
	isPolicyOptionalCategory,
	isPolicyPrompt,
	isPolicyRight,
	isPolicyRuleModel,
	isValidPolicyPromptForModel,
	normalizePolicyRule,
	POLICY_CONSENT_CATEGORIES,
	POLICY_MODEL_PROMPTS,
	POLICY_OPTIONAL_CATEGORIES,
	POLICY_PROMPT_ACTIONS,
	POLICY_PROMPTS,
	POLICY_RIGHTS,
	POLICY_RULE_MODELS,
	type PolicyActionConstraints,
	type PolicyChoiceAction,
	type PolicyConsentCategory,
	type PolicyOptionalCategory,
	type PolicyPrompt,
	type PolicyPromptAction,
	type PolicyRight,
	type PolicyRule,
	type PolicyRuleModel,
	type PolicyRuleReview,
	requiredPolicyRights,
	type ResolvedPolicyRule,
	validatePolicyRules,
} from './policy-rule';
export {
	CHOICE_PROMPT_FINGERPRINT_VERSION,
	type ChoicePromptFingerprintInput,
	choicePromptFingerprintInput,
	createPolicyRuleFingerprints,
	createPresentationFingerprint,
	type JsonValue,
	NOTICE_PROMPT_FINGERPRINT_VERSION,
	type NoticePromptFingerprintInput,
	noticePromptFingerprintInput,
	POLICY_FINGERPRINT_VERSION,
	type PolicyFingerprintInput,
	type PolicyFingerprints,
	policyFingerprintInput,
	PRESENTATION_FINGERPRINT_VERSION,
	type PresentationFingerprintInput,
} from './policy-rule-fingerprint';
export {
	type EuropePolicyRuleMode,
	type PolicyRulePresets,
	policyRulePresets,
} from './policy-rule-presets';
export {
	policyActionConstraintsSchema,
	policyFingerprintsSchema,
	policyOptionalCategorySchema,
	policyPromptActionSchema,
	policyPromptSchema,
	policyResolutionFailureSchema,
	type PolicyResolutionWireOutput,
	policyResolutionWireSchema,
	policyRightSchema,
	policyRuleModelSchema,
	resolvedPolicyRuleSchema,
} from './policy-wire-schema';
export {
	type PolicyI18nMessageProfileLike,
	type PolicyI18nValidationOptions,
	type PolicyI18nValidationResult,
	validatePolicyI18nConfig,
} from './policy-i18n-validation';
export {
	EEA_COUNTRY_CODES,
	EU_COUNTRY_CODES,
	POLICY_MATCH_DATASET_VERSION,
	type PolicyMatch,
	type PolicyMatchedBy,
	type PolicyModel,
	type PolicyScopeMode,
	type PolicyValidationResult,
	policyMatchers,
	UK_COUNTRY_CODES,
} from './policy-runtime';
export {
	compactDefined,
	dedupeDefinedValues,
	dedupeTrimmedStrings,
} from './policy-utils';
export { resolveBackendURL } from './server-url';
export {
	getTranslations,
	getTranslationsData,
	type I18nMessageProfile,
	type I18nMessageProfiles,
	type I18nOptions,
	type LoggerLike,
	listProfiles,
	validateMessages,
} from './translations-runtime';

export type {
	LegacyMaterialCompatibility,
	LegacyMaterialPolicyInput,
	LegacyMaterialSurfaceInput,
} from './legacy-material-policy';
