'use client';

// Generated by scripts/generate-umbrella-exports.ts — do not edit.
export * from '@c15t/react/v3/components/consent-banner';
export { default } from '@c15t/react/v3/components/consent-banner';
