<script>
// Generated by scripts/generate-umbrella-exports.ts — do not edit.
import Component from '@c15t/vue/runtime/components/icons/legitimate-interest-icon.vue';
export default Component;
</script>
