/**
 * The c15t mark as transparent PNGs, one per device-pixel scale.
 *
 * Generated by `scripts/generate-branding-mark.ts` from
 * `C15T_MARK` in `packages/browser/src/ui/branding.ts`, the same path the
 * web badge draws. Do not hand-edit: re-run the script, which rewrites this
 * whole file, so a regenerated mark and the web keep agreeing by construction.
 *
 * The viewBox is 0 0 446 445, so the glyph is about 0.2% taller than wide. Each
 * raster is square because it is drawn into a square viewport, which is far
 * inside the distortion a 15dp mark can show.
 */

/** Device-pixel scales {@link BRANDING_MARK_DATA_URI} carries. */
export const BRANDING_MARK_SCALES = [1, 2, 3] as const;

/** One of {@link BRANDING_MARK_SCALES}. */
export type BrandingMarkScale = (typeof BRANDING_MARK_SCALES)[number];

/** The mark at each scale, as a `data:image/png;base64,` URI. */
export const BRANDING_MARK_DATA_URI: Readonly<
	Record<BrandingMarkScale, string>
> = {
	1: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPCAYAAAA71pVKAAABPklEQVR4nJTTzytEURTA8XumKQtJJFb8D7LzK2HjZ0lWlCRsFHu9WNkQkQgLWzWkLJHCwoa9nY0VpSysppk33zNzN3PnTDNz69N53Tnnnnfvu5NwxojjuAVX+EMKzVZewtnjAN3YRx92rKRkmeIuXIjIFl3reJ6opfgHCxSmNeLOVfPaFGwTevCEATxg3SpOktxBPMUwntGPaV75Jli0yRXOYBKvWBYmH3loxyXW/AK7RqMljOMQs/jQPXciotMRC+ki8xhz9tBDjMjTM9nU4jesMtFGnEIKx0bhov5O3hdxDu/i93zm9/yNBozS4SXYcyNhzzfQPa9IkFBP0IPqxTVacYsTFsuGr1L0qUj4J4zgE0O+Q4QNZ4yS78wCGT+fv2EaMWMVl7theogVb5hYk/qvIpxjEPdOL4TIb5iXAwAA//8vT4crAAAABklEQVQDAPEWdB4hT0T/AAAAAElFTkSuQmCC',
	2: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAC1ElEQVR4nLSXW4hNYRTH1z7OixTRuIXJdUJELg9m5NIUckkMJh4Q04RSoygvygMviswDLyhlXMrLeHIZFGGakjBm3B7ISElKPBi3OX6r/Z1mOZ3L2uFfv7413/72+n/3syclCZXJZFZDR6ZXGtdIQkVJGmOwneJ4gcd1URSdkn9tjOlMivum6j30wHBTNwnzZ450khK/tpl4bzAcAftM/RZxKonxaBM3MrKMQnzY1E8Xp5IYfzTxWMnfoS/yH4xbTHyaNa9WiJtMfbM45dpcGPShOA9rizR7CLOZ/p/iUMkRB9NzJUzbYJ7XVJWW0qZ2pN9hBZRBRah7BJcw7ZEEShuTSooGGAKdEp/Zxca0G5ZjcMOTOHR6MyyAUfABjvB+qz6PQqMNEm+SQmuupst46ab4TPWMX4WpuY+gljwXo7Azr5fItYjGLeIUOXWjTSvSpEqnerepOASNUA7HYEaon0iyH+LTBGOqy6XL9wp2Ga+dOmK9GAZBF6MqN71eQnFZ/k5/zBQ5uyhGwjsd8ddQn7u+7qNRRLnHNbvzU2p8F9ZpT+hRAz08SjmAvw+aF+rhpfikIzoT4v3kaiXnZ8o9Ei+h6pZOdRXBnSKJdEaG8rL7HibnBYraQo9hToqEOuL1oSKf+sI1kvUTv7bCgzz1v2AVnm2R6aWOXHfgYGiXeBYOwPjQRM+wnuVucShcIJtgocQXyBuJLxA9asV/JHhZX7gtvT99V2AljIP5MAw6oJmE3uMmJY2D+RiKe8FE9VbiDWSl01qN+SdxyvuzqD8IuhfKijR7ArMw/yYOuT4ESPZC4vXO6inskPg77HmomwJrxKm0+FVp4ho6o+Y6G7oMj0O9rv9ZR65Exv1N/NrE9mIZKE4l+ebqNHGdietN3C5OJfmgnyzx0ckqe9vNNXUVLIHrak36L4yO9ES+R7AR0yZxKslU6+4+KfGnkJ123VhLk5iqfgMAAP//2yDGuwAAAAZJREFUAwACXfF8LBvz7QAAAABJRU5ErkJggg==',
	3: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAC0AAAAtCAYAAAA6GuKaAAAEnUlEQVR4nMRZa4hWVRRd3yBk9kBKw7KJikp7DQVJRdLMWJg9ycJKzaKoH/6ov9EYZkVZ/4KIIkpMawayEsvxjYoPFHEUHRVfIIr4wgf4GkFhXMt7L57Zc+9477fv4II95zvn7HPOuufu2WeffWtQIjo7O8dRmimbKB1xqfpbKBEVlACSGsxiBmVED2qLKRMqlcphOOEmTcL9WLRT7s6hvp1SR+Ln4UAN/Pge+QgLQylT4YRrp7nLD7DYaprPUr6jtFEepXxK6Wd0arnb+1El+sCH5039JGU4CbXH9VY+2ByWqyg3BnrPUqajSnjN4y5T/yMgfAlx/U+j9yAc8O60xbGM9gOm3h8OeEnvNfWnM/QaTP0QHPCaxyJTr6cNTwobWG9i8cwVxhWC13v0RbTbt5gueZBtiGz3WtPXRjt/DA54Sc9Ddw/SE84h8i5tcKBqmybh/1CMsDDaS1ioyqZJ+B8WL5vmE5R/M4Y0Ux4h4QUoAYV3moT/YvGaaZara5RPZr+O9DuCPtnwKZSISgqpxxG5rocoAyk7KP9z4aXsm8nfb5shR2LC2+AE5x/F4n1E/9j7KJsoqzn32lTSHCCCP1Fez5hTB8Rtpu0gpYGT7oSPbCOLWZSbM1T+pkzkOkeRkOYgkdmI7q6rJ+gh6jnRbjgQXxBacqgqwFJYeyL5R/wdxQjr1Q0vgfAw5CMs3E6Zph99OHAsoqjLQq9LT/cCZYjp20zCe+DH5yltMrXWmKQ8VN+g71XZfYV/5KZGBx3yBCNIanPSQB3thr3nfakulEu6heuOC9Z9mMUydLX1X0VaT3Zv0DieA5vt7NTTw9yE3sMxrjsA3deVt5oZNG2QTV9n9HYhHdvRu8gyt3ZTHyzSR03j0IzB96F3cU9Gu+VzXCfiOkpd0DiZr6SVr+p40sD6FyzsqyvDpj/B5X+0/lxnCtedEqwrc/zKjFkrm36CP9aYDh27ihPkPUai+/VoNie3R3lhcO1fWHxomrcgypHIe8hzWfN9MjlcFE+MQX78QNIfwwmueyuiMOGGnEOaue745HB5D5GZ5MVHXPBrOEECCgPezamuG/0H+lETDz6D6Eo0DfnRROKT4QTXno0oQMuKs3Vx+Jkykrodl8ZYDRLRTflNylOI/LKSMTqh5ODT4uXPOJl71+O16xE9gI53xefLKbM4/+lQr9B1i5O+wmJOSlcTJ54a6N3JYhBlhwIclIzCd0QSepHF3JQukdZbmkC5PmiX3epq1hS6UQ+qutjGwfp8FINSvG+Q+Ao4UfVtnMQVGWrHrykwTLm+ISR+dZI1XHgJIuefBuU91sdlCCUhp8MJb4bpdEqbIrIBfKhhFJ1mM0z/c3xLdXDAS9qmu1aQ6DuJPxX4W4fHSqPXAAe8pGtNfXmG3hJTvx8OeLOmHaY+KENvoKlfgAPenba5jjG01y4X5Dg1MdbotcMBbwJSR7u9RCi18COiRIu+uUxE13yJYonaJIdRDcr4JPctomA+L74h4UlwoKyPn0tZNOZQXUjCo+BEGd8RhZeQHo+EaCmDsFDKTieIvysqUNcRr7SEbvALKb+R8C6UhIsAAAD//11lbzYAAAAGSURBVAMA+fRz/E/YfU0AAAAASUVORK5CYII=',
};

/**
 * Pick the raster for a screen.
 *
 * `PixelRatio.get()` answers 2.75 or 3.5 on real hardware, so the value is
 * rounded and clamped: the nearest raster is the right one, and above 3 there
 * is nothing larger to hand back.
 *
 * @example
 * ```ts
 * Image.source={{ uri: `selectBrandingMark(PixelRatio.get())` }}
 * ```
 *
 * @param pixelRatio - Value from `PixelRatio.get()`.
 * @returns A data URI for the nearest raster.
 */
export const selectBrandingMark = function selectBrandingMark(
	pixelRatio: number
): string {
	const rounded = Math.round(pixelRatio);
	const scale = Math.min(
		3,
		Math.max(1, Number.isFinite(rounded) ? rounded : 1)
	) as BrandingMarkScale;

	return BRANDING_MARK_DATA_URI[scale];
};
