import type { ConsentState, Script, ScriptCallbackInfo } from '@c15t/core';
import { afterEach, beforeEach, expect, vi } from 'vitest';

import { getBuiltInScriptIntegration } from '../registry';
import type { BuiltInScriptIntegrationKey } from '../registry';

/**
 * Typed view of `globalThis` used by script helper tests.
 *
 * Additional string-keyed properties model browser and vendor globals created
 * during setup and individual test cases.
 */
export type TestGlobal = typeof globalThis & Record<string, unknown>;

/**
 * Snapshot of the script fields asserted by helper tests.
 */
export interface HelperScriptSnapshot {
	/** Unique script identifier generated by the helper under test. */
	id: string;
	/** Consent category associated with the script integration. */
	category: unknown;
	/** Whether the script should load even before optional consent is granted. */
	alwaysLoad?: boolean;
	/** Whether the script stays loaded after consent for its category is revoked. */
	persistAfterConsentRevoked?: boolean;
	/** Remote script URL emitted by the helper, when applicable. */
	src?: string;
}

/**
 * Expected integration metadata and script attributes for a helper assertion.
 */
export interface ExpectedScriptSnapshot {
	/** Expected `alwaysLoad` flag from the generated helper script. */
	alwaysLoad: boolean | undefined;
	/** Expected consent-revocation persistence flag from the generated script. */
	persistAfterConsentRevoked: boolean | undefined;
	/** Expected remote script URL from the generated helper script. */
	src: string;
}

/**
 * Consent state with only required storage enabled.
 *
 * `necessary` keeps essential storage on, `functionality` covers site
 * preferences, `measurement` controls analytics, `marketing` controls
 * advertising-related storage, and `experience` controls personalization.
 */
export const deniedConsentState: ConsentState = {
	experience: false,
	functionality: false,
	marketing: false,
	measurement: false,
	necessary: true,
};

/**
 * Consent state with required and measurement storage enabled.
 *
 * `necessary` keeps essential storage on, `functionality` covers site
 * preferences, `measurement` controls analytics, `marketing` controls
 * advertising-related storage, and `experience` controls personalization.
 */
export const grantedMeasurementConsentState: ConsentState = {
	experience: false,
	functionality: false,
	marketing: false,
	measurement: true,
	necessary: true,
};

/**
 * Required callback fields for creating a script lifecycle payload in tests.
 */
export type CallbackInfoOverrides = Partial<ScriptCallbackInfo> &
	Pick<ScriptCallbackInfo, 'id'>;

/**
 * Creates a fully typed callback payload for script lifecycle tests.
 *
 * Defaults model a denied-consent callback for the same DOM element ID as the
 * script ID, while allowing individual tests to override the relevant fields.
 */
export const createCallbackInfo = function createCallbackInfo(
	overrides: CallbackInfoOverrides
): ScriptCallbackInfo {
	return {
		consents: deniedConsentState,
		elementId: overrides.id,
		hasConsent: false,
		...overrides,
	};
};

export type LifecycleCallbackOverrides = Partial<
	Omit<ScriptCallbackInfo, 'id'>
>;

export const runOnBeforeLoad = function runOnBeforeLoad(
	script: Pick<Script, 'id' | 'onBeforeLoad'>,
	overrides: LifecycleCallbackOverrides = {}
): void {
	script.onBeforeLoad?.(
		createCallbackInfo({
			id: script.id,
			...overrides,
		})
	);
};

/**
 * Returns a mutable test-friendly reference to the global object.
 *
 * @returns The current global object cast to `TestGlobal`.
 *
 * @example
 * ```ts
 * const globalRef = getTestGlobal();
 * globalRef.dataLayer = [];
 * ```
 */
export const getTestGlobal = function getTestGlobal(): TestGlobal {
	return globalThis as TestGlobal;
};

const cleanupMockBrowser = function cleanupMockBrowser() {
	const globalRef = getTestGlobal();
	vi.unstubAllGlobals();
	delete globalRef.dataLayer;
	delete globalRef.adobeDataLayer;
	delete globalRef.amplitude;
	delete globalRef._satellite;
	delete globalRef.gtag;
	delete globalRef._paq;
	delete globalRef.mixpanel;
	delete globalRef.analytics;
	delete globalRef.clarity;
	delete globalRef.heap;
	delete globalRef.heapReadyCb;
	delete globalRef.hj;
	delete globalRef._hjSettings;
	delete globalRef.posthog;
	delete globalRef.va;
	delete globalRef.vaq;
	delete globalRef.vam;
	delete globalRef.$crisp;
	delete globalRef.CRISP_WEBSITE_ID;
	delete globalRef.CRISP_RUNTIME_CONFIG;
	delete globalRef.CRISP_COOKIE_DOMAIN;
	delete globalRef.CRISP_COOKIE_EXPIRE;
	delete globalRef.CRISP_TOKEN_ID;
	delete globalRef.Intercom;
	delete globalRef.intercomSettings;
	delete globalRef.databuddy;
	delete globalRef.databuddyConfig;
	delete globalRef.plausible;
	delete globalRef.ttq;
	delete globalRef.snaptr;
	delete globalRef._snaptr;
	delete globalRef.rdt;
	delete globalRef.twq;
	delete globalRef._linkedin_partner_id;
	delete globalRef._linkedin_data_partner_ids;
	delete globalRef.uetq;
	delete globalRef.fbq;
	delete globalRef._fbq;
	delete globalRef.htevents;
	delete globalRef.rudderanalytics;
	delete globalRef.rudderAnalyticsBuildType;
	delete globalRef.RudderSnippetVersion;
};

const setupMockBrowser = function setupMockBrowser() {
	const globalRef = getTestGlobal();
	const scriptAnchor = {
		parentNode: {
			insertBefore: vi.fn((node: Record<string, unknown>) => node),
		},
	};

	const document = {
		createElement: vi.fn((_tag: string) => ({
			async: false,
			defer: false,
			setAttribute: vi.fn(),

			textContent: '',
		})),
		getElementsByTagName: vi.fn(() => [scriptAnchor]),
		head: {
			appendChild: vi.fn((node: Record<string, unknown>) => node),
		},
	};

	vi.stubGlobal('window', globalRef as unknown as Window & typeof globalThis);
	vi.stubGlobal('document', document as unknown as Document);
};

/**
 * Registers browser-like setup and teardown hooks for script helper tests.
 *
 * Before each test, this installs mocked `window` and `document` globals.
 * After each test, it unstubs globals and removes vendor-specific globals left
 * behind by script execution.
 *
 * @returns Nothing.
 *
 * @example
 * ```ts
 * describe('googleTagManager', () => {
 * 	setupScriptHelperTest();
 * });
 * ```
 */
export const setupScriptHelperTest = function setupScriptHelperTest(): void {
	beforeEach(() => {
		setupMockBrowser();
	});

	afterEach(() => {
		cleanupMockBrowser();
	});
};

/**
 * Asserts that a helper-generated script matches registry metadata and
 * expected script fields.
 *
 * @param key - Built-in integration key used to find the registry entry.
 * @param script - Snapshot of the helper-generated script under test.
 * @param expected - Expected script metadata and output for the assertion.
 * @returns Nothing.
 *
 * @remarks
 * If `key` does not match any built-in integration, the assertion fails before
 * the non-null access is used.
 *
 * @example
 * ```ts
 * expectScriptMatchesIntegration(
 * 	'googleTagManager',
 * 	googleTagManager({ id: 'GTM-123' }),
 * 	{
 * 		alwaysLoad: true,
 * 		persistAfterConsentRevoked: undefined,
 * 		src: 'https://www.googletagmanager.com/gtm.js?id=GTM-123',
 * 	}
 * );
 * ```
 */
export const expectScriptMatchesIntegration =
	function expectScriptMatchesIntegration(
		key: BuiltInScriptIntegrationKey,
		script: HelperScriptSnapshot,
		expected: ExpectedScriptSnapshot
	): void {
		const matchedIntegration = getBuiltInScriptIntegration(key);

		expect(script.id, key).toBe(matchedIntegration.vendor);
		expect(script.category, key).toBe(matchedIntegration.consentCategory);
		expect(script.alwaysLoad, key).toBe(expected.alwaysLoad);
		expect(script.persistAfterConsentRevoked, key).toBe(
			expected.persistAfterConsentRevoked
		);
		expect(script.src, key).toBe(expected.src);
	};

/**
 * Converts an array-like value into a plain array.
 *
 * @param value - Array-like input such as `arguments`, a `NodeList`, or a
 * vendor queue entry.
 * @returns A new array containing the indexed values from `value`.
 *
 * @remarks
 * Passing `null` or `undefined` throws because `slice` requires an object-like
 * value.
 *
 * @example
 * ```ts
 * function collectArgs(...args: unknown[]) {
 * 	return toArgumentsArray(args);
 * }
 * ```
 */
export const toArgumentsArray = function toArgumentsArray(
	value: unknown
): unknown[] {
	return Array.prototype.slice.call(value);
};

export const expectGoogleConsentDefault = function expectGoogleConsentDefault(
	entry: unknown
): void {
	expect(toArgumentsArray(entry)).toEqual([
		'consent',
		'default',
		{
			ad_personalization: 'denied',
			ad_storage: 'denied',
			ad_user_data: 'denied',
			analytics_storage: 'denied',
			functionality_storage: 'denied',
			personalization_storage: 'denied',
			security_storage: 'granted',
		},
	]);
};

export const expectStubCommandQueue = function expectStubCommandQueue(
	stub: unknown,
	queueKey: string,
	commands: unknown[][]
): void {
	const queueOwner = stub as Record<string, unknown> | undefined;
	const actualQueue = Array.isArray(queueOwner?.[queueKey])
		? (queueOwner[queueKey] as unknown[]).map((command) =>
				toArgumentsArray(command)
			)
		: queueOwner?.[queueKey];
	expect(actualQueue).toEqual(
		commands.map((command) => toArgumentsArray(command))
	);
};
