/**
 * One group of `@c15t/react`'s public exports. The package index re-exports
 * each group with `export *`, so a bundler that splits code by reachability
 * (esbuild) does not treat every module the index names as part of an app
 * that imports one hook: only the groups it uses are live.
 */
export {
	useActiveUI,
	useBranding,
	useConsent,
	useConsents,
	useDeclaredVendors,
	useDismissNotice,
	useEffectivePermissions,
	useExperiment,
	useExplicitChoice,
	useHasConsentPolicy,
	useHasConsentPreferences,
	useHasConsentUI,
	useIABEnabled,
	useIABSnapshot,
	useIdentify,
	useInit,
	useLocation,
	useModel,
	useNoticeDismissal,
	useOverrides,
	usePolicyCategories,
	usePolicyResolution,
	usePolicyRule,
	usePolicyScopeMode,
	usePreferencesPresentation,
	usePrivacySignals,
	usePromptPresentation,
	usePromptRequirement,
	usePurposeConsent,
	useRegisterConsentCategories,
	useResolvedPresentation,
	useResolvedTheme,
	useRestrictions,
	useSaveConsents,
	useSetActiveUI,
	useSetLanguage,
	useSetOverrides,
	useSnapshot,
	useSpecialFeatureOptIn,
	useSubscribeToConsentChanges,
	useTCString,
	useUser,
	useVendorAllowed,
	useVendorChoice,
	useVendorConsent,
} from '../hooks';
