/**
 * Generates `src/generated/styles.ts` from the built `@c15t/ui` artifacts.
 *
 * The script-tag build has to carry the stylesheet as a string so it can
 * drop it into a shadow root, and it needs the hashed class names without
 * importing the CSS-module JS (whose `import './x.css'` side effect would
 * make the bundler emit a separate stylesheet). Reading both from the
 * published `dist/` of `@c15t/ui` keeps this package's DOM in lockstep
 * with the React, Svelte and Vue surfaces: same classes, same tokens.
 *
 * Runs from `prebuild`; the output is gitignored.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const uiDist = dirname(
	fileURLToPath(import.meta.resolve('@c15t/ui/styles.css'))
);
const outputDir = resolve(import.meta.dirname, '../src/generated');

/** Component style maps the vanilla surfaces render against. */
const COMPONENTS = {
	accordion: 'accordion',
	actions: 'consent-actions',
	banner: 'consent-banner',
	branding: 'branding',
	button: 'button',
	dialog: 'consent-dialog',
	legalLinks: 'legal-links',
	manager: 'consent-manager',
	switch: 'switch',
	trigger: 'consent-dialog-trigger',
} as const;

const readClassMap = async function readClassMap(
	component: string
): Promise<Record<string, string>> {
	// The `.node.js` variant is the class map without the CSS import.
	const source = await readFile(
		join(uiDist, 'styles', 'components', `${component}.node.js`),
		'utf8'
	);
	const match = /export default(?<map>\{.*\});?\s*$/su.exec(source);
	if (!match?.groups?.map) {
		throw new Error(
			`@c15t/browser: could not parse class map for ${component}`
		);
	}
	// The map is a plain object literal with unquoted keys; JSON needs quotes.
	const json = match.groups.map
		.replace(
			/(?<before>[{,])\s*(?<key>[A-Za-z0-9_$-]+)\s*:/gu,
			'$<before>"$<key>":'
		)
		.replace(/'/gu, '"');
	return JSON.parse(json) as Record<string, string>;
};

const main = async function main(): Promise<void> {
	// The sheet already pairs every `:root` with `:host`, so it applies
	// inside the shadow root as published.
	const stylesheet = await readFile(join(uiDist, 'styles.css'), 'utf8');
	const entries = await Promise.all(
		Object.entries(COMPONENTS).map(async ([key, component]) => [
			key,
			await readClassMap(component),
		])
	);
	const classes = Object.fromEntries(entries) as Record<
		keyof typeof COMPONENTS,
		Record<string, string>
	>;

	const banner = [
		'// Generated by scripts/build-styles.ts from the built @c15t/ui package.',
		'// Do not edit; rerun `bun prebuild`.',
		'',
	].join('\n');
	const body = [
		`export const stylesheet: string = ${JSON.stringify(stylesheet)};`,
		'',
		`export const classes = ${JSON.stringify(classes, null, '\t')} as const;`,
		'',
	].join('\n');

	await mkdir(outputDir, { recursive: true });
	await writeFile(join(outputDir, 'styles.ts'), `${banner}\n${body}`);
};

await main();
