/**
 * Write the CLI version into the generation source. Hosts compile
 * `src/generate` and `src/frontend` without package.json or Node built-ins,
 * so the release line they install from has to be a source constant.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const manifestPath = new URL('../package.json', import.meta.url);
const targetPath = new URL('../src/generate/version.ts', import.meta.url);
const { version } = JSON.parse(readFileSync(manifestPath, 'utf8')) as {
	version: string;
};
const contents = `// Generated by scripts/write-version.ts from package.json. Do not edit.

/** Version of the @c15t/cli release this source was published with. */
export const version = '${version}';
`;

let current = '';
try {
	current = readFileSync(targetPath, 'utf8');
} catch {
	// First build: the file does not exist yet.
}
if (current !== contents) {
	writeFileSync(targetPath, contents);
}
