import { defineDocsConfig } from 'leadtype';

export default defineDocsConfig({
	groups: [
		{
			slug: 'frameworks',
			title: 'Frameworks',
		},
		{
			slug: 'concepts',
			title: 'Concepts',
		},
		{
			slug: 'guides',
			title: 'Guides',
		},
		{
			slug: 'customization',
			title: 'Customization',
		},
		{
			slug: 'integrations',
			title: 'Integrations',
		},
		{
			slug: 'cli',
			title: 'CLI',
		},
		{
			slug: 'self-host',
			title: 'Backend',
		},
		{
			slug: 'reference',
			title: 'Reference',
		},
		{
			slug: 'changelog',
			title: 'Changelog',
		},
	],
	llms: {
		sections: [
			{
				body: "These docs describe c15t v3. Find your app's row in Choose your setup, then follow that framework guide from start to finish; it names the files to create and the backend URL to use. Install c15t packages with the @alpha dist-tag, because npm latest is still v2. A visible banner does not prove anything: check that vendor requests wait for consent, that rejection survives a reload, and that preferences can be reopened.",
				heading: 'Using these docs',
				type: 'markdown',
			},
			{
				heading: 'Start here',
				links: [
					{
						urlPath: '/docs/concepts/choose-your-setup',
					},
					{
						urlPath: '/docs/concepts/how-consent-works',
					},
					{
						urlPath: '/docs/customization/overview',
					},
					{
						urlPath: '/docs/guides/verify-consent',
					},
					{
						urlPath: '/docs/upgrade-v3',
					},
				],
				type: 'links',
			},
			{
				body: '[Documentation index](https://c15t.com/docs/llms.txt) · [Full Markdown context](https://c15t.com/llms-full.txt). Prefer the index and individual pages for focused tasks.',
				heading: 'More documentation',
				type: 'markdown',
			},
		],
	},
	navigation: [
		{
			pages: ['index', 'concepts/choose-your-setup', 'examples', 'upgrade-v3'],
			title: 'Getting started',
		},
		{
			base: 'concepts',
			pages: [
				'how-consent-works',
				'consent-categories',
				'policies',
				'modes',
				'data-fetching',
				'consent-state',
			],
			title: 'Concepts',
		},
		{
			base: 'customization',
			pages: [
				'overview',
				'recipes',
				'tokens',
				'dark-mode',
				'motion',
				'stylesheets',
				'slots',
				'class-names',
				'tailwind',
				'translations',
				'/guides/banner-experiments',
			],
			title: 'Customization',
		},
		{
			base: 'guides',
			pages: ['verify-consent', 'troubleshooting'],
			title: 'Verify and troubleshoot',
		},
		{
			base: 'frameworks',
			children: [
				{
					base: 'next',
					children: [
						{
							pages: [
								'scripts',
								'embeds',
								'network-blocker',
								'vendor-consent',
								'clear-on-revocation',
							],
							slug: 'scripts-and-embeds',
							title: 'Scripts and embeds',
						},
						{
							pages: [
								'customize',
								'/customization/recipes',
								'/customization/tokens',
								'/customization/dark-mode',
								'/customization/tailwind',
								'translations',
								'compose',
								'headless',
							],
							slug: 'customization',
							title: 'Customization',
						},
						{
							pages: [
								'components',
								'components/consent-root',
								'components/consent-banner',
								'components/consent-dialog',
								'components/consent-widget',
								'components/consent-dialog-link',
								'components/consent-dialog-trigger',
								'components/consent-gate',
							],
							slug: 'components',
							title: 'Components',
						},
						{
							pages: ['hooks', 'callbacks'],
							slug: 'consent-api',
							title: 'Consent API',
						},
						{
							pages: [
								'iab',
								'gpp',
								'geography-headers',
								'content-security-policy',
								'optimization',
								'data-fetching-reference',
							],
							slug: 'advanced',
							title: 'Advanced',
						},
						{
							pages: [
								'components/dev-tools',
								'troubleshooting',
								'/guides/verify-consent',
							],
							slug: 'verify-and-troubleshoot',
							title: 'Verify and troubleshoot',
						},
					],
					pages: [
						'quickstart',
						'app-router',
						'pages-router',
						'static-export',
						'client-side',
						'rendering',
						'upgrade-v3',
					],
					slug: 'next',
					title: 'Next.js',
				},
				{
					base: 'tanstack-start',
					children: [
						{
							pages: [
								'scripts',
								'embeds',
								'network-blocker',
								'vendor-consent',
								'clear-on-revocation',
							],
							slug: 'scripts-and-embeds',
							title: 'Scripts and embeds',
						},
						{
							pages: [
								'customize',
								'/customization/recipes',
								'/customization/tokens',
								'/customization/dark-mode',
								'/customization/tailwind',
								'translations',
								'compose',
								'headless',
							],
							slug: 'customization',
							title: 'Customization',
						},
						{
							pages: [
								'components',
								'components/consent-banner',
								'components/consent-dialog',
								'components/consent-widget',
								'components/consent-dialog-link',
								'components/consent-dialog-trigger',
								'components/consent-gate',
							],
							slug: 'components',
							title: 'Components',
						},
						{
							pages: ['hooks', 'callbacks'],
							slug: 'consent-api',
							title: 'Consent API',
						},
						{
							pages: [
								'iab',
								'gpp',
								'geography-headers',
								'content-security-policy',
							],
							slug: 'advanced',
							title: 'Advanced',
						},
						{
							pages: [
								'components/dev-tools',
								'troubleshooting',
								'/guides/verify-consent',
							],
							slug: 'verify-and-troubleshoot',
							title: 'Verify and troubleshoot',
						},
					],
					pages: ['quickstart', 'rendering'],
					slug: 'tanstack-start',
					title: 'TanStack Start',
				},
				{
					base: 'react',
					children: [
						{
							pages: [
								'scripts',
								'embeds',
								'network-blocker',
								'vendor-consent',
								'clear-on-revocation',
							],
							slug: 'scripts-and-embeds',
							title: 'Scripts and embeds',
						},
						{
							pages: [
								'customize',
								'/customization/recipes',
								'/customization/tokens',
								'/customization/dark-mode',
								'/customization/tailwind',
								'translations',
								'compose',
								'headless',
							],
							slug: 'customization',
							title: 'Customization',
						},
						{
							pages: [
								'components',
								'components/consent-provider',
								'components/consent-banner',
								'components/consent-dialog',
								'components/consent-widget',
								'components/consent-dialog-link',
								'components/consent-dialog-trigger',
								'components/consent-gate',
							],
							slug: 'components',
							title: 'Components',
						},
						{
							pages: ['hooks', 'callbacks'],
							slug: 'consent-api',
							title: 'Consent API',
						},
						{
							pages: ['iab', 'gpp', 'content-security-policy'],
							slug: 'advanced',
							title: 'Advanced',
						},
						{
							pages: [
								'components/dev-tools',
								'troubleshooting',
								'/guides/verify-consent',
							],
							slug: 'verify-and-troubleshoot',
							title: 'Verify and troubleshoot',
						},
					],
					pages: ['quickstart', 'rendering', 'upgrade-v3'],
					slug: 'react',
					title: 'React',
				},
				{
					base: 'nuxt',
					children: [
						{
							pages: [
								'scripts',
								'embeds',
								'network-blocker',
								'vendor-consent',
								'clear-on-revocation',
							],
							slug: 'scripts-and-embeds',
							title: 'Scripts and embeds',
						},
						{
							pages: [
								'customize',
								'/customization/recipes',
								'/customization/tokens',
								'/customization/dark-mode',
								'/customization/tailwind',
								'translations',
								'headless',
							],
							slug: 'customization',
							title: 'Customization',
						},
						{
							pages: [
								'components',
								'components/consent-root',
								'components/consent-banner',
								'components/consent-manager',
								'components/consent-widget',
								'components/consent-dialog-link',
								'components/consent-dialog-trigger',
								'components/consent-gate',
								'components/iab-consent-banner',
								'components/iab-consent-dialog',
							],
							slug: 'components',
							title: 'Components',
						},
						{
							pages: ['composables', 'callbacks'],
							slug: 'consent-api',
							title: 'Consent API',
						},
						{
							pages: [
								'iab',
								'gpp',
								'geography-headers',
								'content-security-policy',
							],
							slug: 'advanced',
							title: 'Advanced',
						},
						{
							pages: [
								'components/dev-tools',
								'troubleshooting',
								'/guides/verify-consent',
							],
							slug: 'verify-and-troubleshoot',
							title: 'Verify and troubleshoot',
						},
					],
					pages: ['quickstart', 'module', 'rendering'],
					slug: 'nuxt',
					title: 'Nuxt',
				},
				{
					base: 'vue',
					children: [
						{
							pages: [
								'scripts',
								'embeds',
								'network-blocker',
								'vendor-consent',
								'clear-on-revocation',
							],
							slug: 'scripts-and-embeds',
							title: 'Scripts and embeds',
						},
						{
							pages: [
								'customize',
								'/customization/recipes',
								'/customization/tokens',
								'/customization/dark-mode',
								'/customization/tailwind',
								'translations',
								'headless',
							],
							slug: 'customization',
							title: 'Customization',
						},
						{
							pages: [
								'components',
								'components/consent-root',
								'components/consent-banner',
								'components/consent-manager',
								'components/consent-widget',
								'components/consent-dialog-link',
								'components/consent-dialog-trigger',
								'components/consent-gate',
								'components/iab-consent-banner',
								'components/iab-consent-dialog',
							],
							slug: 'components',
							title: 'Components',
						},
						{
							pages: ['composables', 'callbacks'],
							slug: 'consent-api',
							title: 'Consent API',
						},
						{
							pages: ['iab', 'gpp', 'content-security-policy'],
							slug: 'advanced',
							title: 'Advanced',
						},
						{
							pages: [
								'components/dev-tools',
								'troubleshooting',
								'/guides/verify-consent',
							],
							slug: 'verify-and-troubleshoot',
							title: 'Verify and troubleshoot',
						},
					],
					pages: ['quickstart', 'plugin', 'rendering'],
					slug: 'vue',
					title: 'Vue',
				},
				{
					base: 'astro',
					children: [
						{
							pages: [
								'scripts',
								'embeds',
								'network-blocker',
								'vendor-consent',
								'clear-on-revocation',
							],
							slug: 'scripts-and-embeds',
							title: 'Scripts and embeds',
						},
						{
							pages: [
								'customize',
								'/customization/recipes',
								'/customization/tokens',
								'/customization/dark-mode',
								'/customization/tailwind',
								'translations',
							],
							slug: 'customization',
							title: 'Customization',
						},
						{
							pages: [
								'components',
								'components/consent-script',
								'components/consent-banner',
								'components/consent-banner-deferred',
								'components/consent-dialog',
								'components/consent-dialog-link',
								'components/iab-consent-banner',
								'components/iab-consent-dialog',
							],
							slug: 'components',
							title: 'Components',
						},
						{
							pages: ['client-api', 'callbacks'],
							slug: 'consent-api',
							title: 'Consent API',
						},
						{
							pages: [
								'iab',
								'gpp',
								'geography-headers',
								'content-security-policy',
								'islands',
							],
							slug: 'advanced',
							title: 'Advanced',
						},
						{
							pages: ['integration', 'server'],
							slug: 'reference',
							title: 'Reference',
						},
						{
							pages: ['troubleshooting', '/guides/verify-consent'],
							slug: 'verify-and-troubleshoot',
							title: 'Verify and troubleshoot',
						},
					],
					pages: ['quickstart', 'rendering'],
					slug: 'astro',
					title: 'Astro',
				},
				{
					base: 'svelte',
					children: [
						{
							pages: [
								'scripts',
								'embeds',
								'network-blocker',
								'vendor-consent',
								'clear-on-revocation',
							],
							slug: 'scripts-and-embeds',
							title: 'Scripts and embeds',
						},
						{
							pages: [
								'customize',
								'/customization/recipes',
								'/customization/tokens',
								'/customization/dark-mode',
								'/customization/tailwind',
								'translations',
								'components/primitives',
								'headless',
							],
							slug: 'customization',
							title: 'Customization',
						},
						{
							pages: [
								'components',
								'components/consent-provider',
								'components/consent-banner',
								'components/consent-dialog',
								'components/consent-widget',
								'components/consent-dialog-link',
								'components/consent-dialog-trigger',
								'components/consent-gate',
								'components/consent-button',
								'components/iab-consent-banner',
								'components/iab-consent-dialog',
							],
							slug: 'components',
							title: 'Components',
						},
						{
							pages: ['getters', 'callbacks'],
							slug: 'consent-api',
							title: 'Consent API',
						},
						{
							pages: ['iab', 'gpp', 'content-security-policy'],
							slug: 'advanced',
							title: 'Advanced',
						},
						{
							pages: [
								'components/dev-tools',
								'troubleshooting',
								'/guides/verify-consent',
							],
							slug: 'verify-and-troubleshoot',
							title: 'Verify and troubleshoot',
						},
					],
					pages: ['quickstart'],
					slug: 'svelte',
					title: 'Svelte',
				},
				{
					base: 'sveltekit',
					children: [
						{
							pages: [
								'scripts',
								'embeds',
								'network-blocker',
								'vendor-consent',
								'clear-on-revocation',
							],
							slug: 'scripts-and-embeds',
							title: 'Scripts and embeds',
						},
						{
							pages: [
								'customize',
								'/customization/recipes',
								'/customization/tokens',
								'/customization/dark-mode',
								'/customization/tailwind',
								'translations',
								'components/primitives',
								'headless',
							],
							slug: 'customization',
							title: 'Customization',
						},
						{
							pages: [
								'components',
								'components/consent-root',
								'components/consent-banner',
								'components/consent-dialog',
								'components/consent-widget',
								'components/consent-dialog-link',
								'components/consent-dialog-trigger',
								'components/consent-gate',
								'components/consent-button',
								'components/iab-consent-banner',
								'components/iab-consent-dialog',
							],
							slug: 'components',
							title: 'Components',
						},
						{
							pages: ['getters', 'callbacks'],
							slug: 'consent-api',
							title: 'Consent API',
						},
						{
							pages: [
								'iab',
								'gpp',
								'geography-headers',
								'content-security-policy',
								'server-api',
							],
							slug: 'advanced',
							title: 'Advanced',
						},
						{
							pages: [
								'components/dev-tools',
								'troubleshooting',
								'/guides/verify-consent',
							],
							slug: 'verify-and-troubleshoot',
							title: 'Verify and troubleshoot',
						},
					],
					pages: ['quickstart', 'rendering'],
					slug: 'sveltekit',
					title: 'SvelteKit',
				},
				{
					base: 'html',
					children: [
						{
							pages: [
								'scripts',
								'embeds',
								'network-blocker',
								'vendor-consent',
								'clear-on-revocation',
							],
							slug: 'scripts-and-embeds',
							title: 'Scripts and embeds',
						},
						{
							pages: [
								'customize',
								'/customization/recipes',
								'/customization/tokens',
								'/customization/dark-mode',
								'/customization/tailwind',
								'translations',
								'headless',
							],
							slug: 'customization',
							title: 'Customization',
						},
						{
							pages: [
								'components',
								'components/banner',
								'components/dialog',
								'components/trigger',
								'components/action-buttons',
								'components/preferences-link',
								'components/gated-script',
							],
							slug: 'components',
							title: 'Components',
						},
						{
							pages: ['api', 'callbacks'],
							slug: 'consent-api',
							title: 'Consent API',
						},
						{
							pages: ['iab', 'gpp', 'content-security-policy'],
							slug: 'advanced',
							title: 'Advanced',
						},
						{
							pages: ['attributes-and-api', 'configuration'],
							slug: 'reference',
							title: 'Reference',
						},
						{
							pages: ['dev-tools', 'troubleshooting', '/guides/verify-consent'],
							slug: 'verify-and-troubleshoot',
							title: 'Verify and troubleshoot',
						},
					],
					pages: ['quickstart', 'platforms'],
					slug: 'html',
					title: 'HTML',
				},
				{
					base: 'javascript',
					children: [
						{
							pages: [
								'scripts',
								'modules/iframe-blocker',
								'modules/network-blocker',
								'vendor-consent',
								'clear-on-revocation',
							],
							slug: 'scripts-and-embeds',
							title: 'Scripts and embeds',
						},
						{
							pages: [
								'customize',
								'/customization/recipes',
								'/customization/tokens',
								'/customization/dark-mode',
								'/customization/tailwind',
								'translations',
								'headless',
							],
							slug: 'customization',
							title: 'Customization',
						},
						{
							pages: ['api/browser', 'callbacks'],
							slug: 'consent-api',
							title: 'Consent API',
						},
						{
							pages: ['iab', 'gpp', 'transports', 'content-security-policy'],
							slug: 'advanced',
							title: 'Advanced',
						},
						{
							pages: [
								'api/browser-options',
								'api/runtime',
								'api/kernel',
								'api/snapshot',
								'modules/script-loader',
								'modules/persistence',
							],
							slug: 'reference',
							title: 'Reference',
						},
						{
							pages: ['dev-tools', 'troubleshooting', '/guides/verify-consent'],
							slug: 'verify-and-troubleshoot',
							title: 'Verify and troubleshoot',
						},
					],
					pages: ['quickstart', 'upgrade-v3'],
					slug: 'javascript',
					title: 'JavaScript',
				},
			],
			pages: ['index'],
			slug: 'frameworks',
			title: 'Frameworks',
		},
		{
			base: 'integrations',
			children: [
				{
					pages: ['google-maps', 'youtube'],
					slug: 'embeds',
					title: 'Embeds',
				},
				{
					pages: ['google-tag-manager', 'cloudflare-zaraz'],
					slug: 'tag-managers',
					title: 'Tag managers',
				},
				{
					pages: [
						'google-tag',
						'ahrefs-analytics',
						'adobe-analytics',
						'amplitude',
						'cloudflare-web-analytics',
						'clearbit',
						'microsoft-clarity',
						'databuddy',
						'fathom-analytics',
						'heap',
						'matomo-analytics',
						'mixpanel-analytics',
						'one-dollar-stats',
						'hotjar',
						'hightouch',
						'logrocket',
						'plausible-analytics',
						'posthog',
						'promptwatch',
						'pirsch',
						'rudderstack',
						'segment',
						'sentry',
						'rybbit-analytics',
						'umami-analytics',
						'vercel-analytics',
					],
					slug: 'analytics',
					title: 'Analytics',
				},
				{
					pages: ['crisp', 'front-chat', 'intercom'],
					slug: 'chat-and-support',
					title: 'Chat and support',
				},
				{
					pages: ['klaviyo'],
					slug: 'email-and-sms',
					title: 'Email and SMS',
				},
				{
					pages: [
						'meta-pixel',
						'openai-pixel',
						'pinterest-tag',
						'reddit-pixel',
						'tiktok-pixel',
						'linkedin-insights',
						'microsoft-uet',
						'snapchat-pixel',
						'x-pixel',
					],
					slug: 'ads-and-pixels',
					title: 'Ads and pixels',
				},
			],
			pages: ['overview', 'building-integrations'],
			slug: 'integrations',
			title: 'Integrations',
		},
		{
			base: 'self-host',
			children: [
				{
					pages: [
						'guides/database-setup',
						'guides/policy-packs',
						'guides/caching',
						'guides/edge-deployment',
						'guides/iab-tcf',
						'guides/legal-document-snapshot-integration',
						'guides/observability',
					],
					slug: 'guides',
					title: 'Guides',
				},
				{
					pages: ['api/configuration', 'api/endpoints', 'api/node-sdk'],
					slug: 'reference',
					title: 'Reference',
				},
			],
			pages: ['overview', 'quickstart'],
			slug: 'self-host',
			title: 'Backend',
		},
		{
			base: 'cli',
			children: [
				{
					pages: [
						'commands/setup',
						'commands/boilerplate',
						'commands/codemods',
						'commands/hosted',
						'commands/self-host',
						'global-flags',
					],
					slug: 'commands',
					title: 'Commands',
				},
			],
			pages: ['overview', 'quickstart', 'automation'],
			slug: 'cli',
			title: 'CLI',
		},
		{
			base: 'comparisons',
			pages: [
				'index',
				'build-your-own',
				'axeptio',
				'borlabs-cookie',
				'complianz',
				'consentmanager',
				'cookie-control',
				'cookiebot',
				'cookieconsent-v3',
				'cookiefirst',
				'cookiehub',
				'cookiescript',
				'cookieyes',
				'didomi',
				'enzuzo',
				'ethyca',
				'iubenda',
				'ketch',
				'klaro',
				'onetrust',
				'osano',
				'react-cookie-consent',
				'silktide-consent-manager',
				'sourcepoint',
				'tarteaucitron',
				'termly',
				'trustarc',
				'usercentrics',
			],
			title: 'Comparisons',
		},
		{
			pages: [
				'contributing/index',
				'oss/why-open-source',
				'oss/contributing',
				'oss/code-of-conduct',
				'oss/license',
			],
			title: 'Project',
		},
		{
			base: 'legals',
			optional: true,
			pages: ['cookie-policy', 'privacy-policy'],
			title: 'Legal',
		},
	],
	product: {
		docs: 'https://c15t.com/docs',
		homepage: 'https://c15t.com',
		kind: 'library',
		name: 'c15t',
		repository: 'https://github.com/c15t/c15t',
		tagline:
			'Consent management for React, Next.js, Vue, Nuxt, Svelte, SvelteKit, Astro, TanStack Start and JavaScript.',
	},
});
