import Foundation
import XCTest

// ---------------------------------------------------------------------------
// PROVISIONAL CORPUS. The shared tc-string fixtures live in `native/protocol`,
// owned by the vectors lane. This array exists only while those have not landed.
// `TcFixtureCorpus` is the ONLY accessor this target reads TC strings through,
// so swapping in the shared fixtures is one edit here and nothing elsewhere.
// Do not add TC string literals anywhere else in this test target.
// ---------------------------------------------------------------------------

/// A TC String produced by the reference implementation, with what the reference
/// itself reported about it.
struct TcOracleVector {
        /// Short stable name, used in assertion messages.
        let id: String
        /// What this build must do with the string.
        let expectation: TcOracleVectorExpectation
        /// Whether `TCString.decode` accepts it.
        let oracleDecodes: Bool?
        /// Whether the reference reproduces its own bytes. `nil` means it could not
        /// re-encode the string at all.
        let oracleByteExact: Bool?
        let note: String
        let string: String
}

enum TcOracleVectorExpectation: String {
        /// decode, then encode, then require the same bytes.
        case roundtrip
        /// decode only: the reference cannot encode this shape, so encode is not
        /// claimed against it.
        case decodeOnly
        /// must be refused.
        case reject
}

/// The only place this test target obtains TC strings.
///
/// Generated by gen.mjs against @iabtechlabtcf/core 1.5.21. Regenerate it rather
/// than hand-edit: the reference verdicts are part of the data.
enum TcFixtureCorpus {
        static var all: [TcOracleVector] { provisional }

        static func vectors(_ expectation: TcOracleVectorExpectation) -> [TcOracleVector] {
                provisional.filter { $0.expectation == expectation }
        }

        static func vector(
                _id id: String,
                file: StaticString = #filePath,
                line: UInt = #line
        ) -> TcOracleVector {
                guard let found = provisional.first(where: { $0.id == id }) else {
                        XCTFail("no TC fixture vector named "+id, file: file, line: line)
                        return TcOracleVector(
                                id: id, expectation: .reject, oracleDecodes: nil, oracleByteExact: nil,
                                note: "not in the corpus", string: ""
                        )
                }
                return found
        }

        private static let provisional: [TcOracleVector] = [
        TcOracleVector(
                id: "core-empty",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: true,
        note: "every vector empty",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA"),
        TcOracleVector(
                id: "core-purposes",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: true,
        note: "sparse purposes and vendors",
        string: "CQeGKnQQeGKnQAcABDENCxFgAMBAAAKAACiQAEIEABwEAAAA"),
        TcOracleVector(
                id: "core-all-flags",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: true,
        note: "full purposes, both feature opt-ins, every boolean",
        string: "CQeGKnQQeGKnQAcABDENCxFcAP_gAAPgAKiQAAAAAAAA"),
        TcOracleVector(
                id: "core-max-ints",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: true,
        note: "every int field at its ceiling",
        string: "CQeGKnQQeGKnQ_____DE___gAAAAAAAAAAqIAAAAAAAA"),
        TcOracleVector(
                id: "core-date-extremes",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: true,
        note: "epoch floor and high date, AA/ZZ language codes",
        string: "CQdWToATZa7X_AcABDAACxFgAAAAAAAAADLIAAAAAAAA"),
        TcOracleVector(
                id: "disclosed-bitfield",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: true,
        note: "5 contiguous vendors",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA.IACvgAAA"),
        TcOracleVector(
                id: "disclosed-mixed-ranges",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: true,
        note: "6 vendors in three disjoint runs",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA.IDhQA4AAgAHAAcACADhA"),
        TcOracleVector(
                id: "disclosed-bitfield-45",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: true,
        note: "45 contiguous: largest bitfield the encoder keeps",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA.IAWv______-A"),
        TcOracleVector(
                id: "disclosed-range-46",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: true,
        note: "46 contiguous: first size where range wins",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA.IAXQAYAAgBcA"),
        TcOracleVector(
                id: "disclosed-range-500",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: true,
        note: "500 contiguous vendors",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA.ID6QAYAAgPoA"),
        TcOracleVector(
                id: "disclosed-single-high",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: true,
        note: "one vendor at id 500",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA.ID6QAQD6AAAA"),
        TcOracleVector(
                id: "allowed-and-disclosed",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: true,
        note: "OOB allowed alongside disclosed",
        string: "CQeGKnQQeGKnQAcABDENCxFAAAAAAAAAACiQAAAAAAAA.ICWQAwACwAoACoAlgAAA.QCWQAwACwAoACoAlgAAA"),
        TcOracleVector(
                id: "publisher-tc",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: true,
        note: "publisher consents, LI, and 6 custom purposes",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA.cgAADAAAA1KQ"),
        TcOracleVector(
                id: "publisher-tc-one-custom",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: true,
        note: "a single custom purpose",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA.YAAAAAAAAMAA"),
        TcOracleVector(
                id: "core-restrictions",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: nil,
        note: "two restrictions, one with a gap in the vendor run",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAABCIAUABAAGAASPAAwAUABY"),
        TcOracleVector(
                id: "restrictions-with-disclosed",
                expectation: .roundtrip,
                oracleDecodes: true,
                oracleByteExact: nil,
        note: "restrictions alongside a disclosed vendor list",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAhgAMABAAF.IDhQAwABgAJAOEAA"),
        TcOracleVector(
                id: "lossy-disclosed-maxid",
                expectation: .decodeOnly,
                oracleDecodes: true,
                oracleByteExact: nil,
        note: "declared NumVendors=700 with only 3 and 9 set: the oracle drops the declared width on decode",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA.IFeCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
        TcOracleVector(
                id: "lossy-disclosed-maxid-range",
                expectation: .decodeOnly,
                oracleDecodes: true,
                oracleByteExact: nil,
        note: "range encoding declaring NumVendors=600 with only the run 3..9",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA.IEsQAYABgASA"),
        TcOracleVector(
                id: "bad-non-base64url",
                expectation: .reject,
                oracleDecodes: false,
                oracleByteExact: nil,
        note: "a character outside the base64url set",
        string: "BO!A"),
        TcOracleVector(
                id: "bad-empty-string",
                expectation: .reject,
                oracleDecodes: false,
                oracleByteExact: nil,
        note: "the empty string",
        string: ""),
        TcOracleVector(
                id: "bad-unknown-segment-type",
                expectation: .reject,
                oracleDecodes: false,
                oracleByteExact: nil,
        note: "segment type 7 is unassigned",
        string: "4AAAAAAAAAAA"),
        TcOracleVector(
                id: "bad-version-3",
                expectation: .reject,
                oracleDecodes: false,
                oracleByteExact: nil,
        note: "version bits say 3, this build speaks 2",
        string: "DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
        TcOracleVector(
                id: "bad-version-0",
                expectation: .reject,
                oracleDecodes: false,
                oracleByteExact: nil,
        note: "version bits are zero",
        string: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
        TcOracleVector(
                id: "bad-truncated-core",
                expectation: .reject,
                oracleDecodes: false,
                oracleByteExact: nil,
        note: "core segment shorter than the v2 field sequence",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAA"),
        TcOracleVector(
                id: "bad-short-bitfield",
                expectation: .reject,
                oracleDecodes: false,
                oracleByteExact: nil,
        note: "bit field declares 64 ids but only 20 bits follow",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA.IAgP__8A"),
        TcOracleVector(
                id: "bad-reversed-vendor-range",
                expectation: .reject,
                oracleDecodes: true,
                oracleByteExact: nil,
        note: "a range entry whose end id is below its start id",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA.IAeQAYAEgAGA"),
        TcOracleVector(
                id: "bad-invalid-language",
                expectation: .reject,
                oracleDecodes: true,
                oracleByteExact: nil,
        note: "language bits decode outside A-Z",
        string: "CAAAATSAAAATSAcABBaACxFAAAAAAAAAAAAAAAAAAAAA"),
        TcOracleVector(
                id: "bad-invalid-country-code",
                expectation: .reject,
                oracleDecodes: true,
                oracleByteExact: nil,
        note: "publisher country bits decode outside A-Z",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAADSQAAAAAAAA"),
        TcOracleVector(
                id: "bad-duplicate-segment",
                expectation: .reject,
                oracleDecodes: true,
                oracleByteExact: nil,
        note: "the same segment type appears twice",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA.IAEiCAAA.IAEiCAAA"),
        TcOracleVector(
                id: "bad-core-not-first",
                expectation: .reject,
                oracleDecodes: true,
                oracleByteExact: nil,
        note: "a vendor list segment precedes the core segment",
        string: "IAEiCAAA.CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAA"),
        TcOracleVector(
                id: "bad-restriction-range",
                expectation: .reject,
                oracleDecodes: false,
                oracleByteExact: nil,
        note: "a publisher restriction range whose end id is below its start id",
        string: "CQeGKnQQeGKnQAcABDENCxFgAAAAAAAAACiQAAAAAAAiIAMABwAD"),
        ]
}
