/**
 * Build step for the static export: fetches the backend `/manifest` once
 * and writes it as a typed module the app bundles, which is what
 * `createStaticManifestModule` exists for. Runs before `next build` from
 * this cell's `build` script.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { createStaticManifestModule } from '@c15t/nextjs/static';

const backendURL = process.env.NEXT_PUBLIC_COMPAT_BACKEND_URL;
if (!backendURL) {
	throw new Error(
		'NEXT_PUBLIC_COMPAT_BACKEND_URL is not set. The compat suite sets it ' +
			'to the standalone stub; run `bun run test:compat` instead of ' +
			'`bun run build`.'
	);
}

const target = resolve(
	dirname(fileURLToPath(import.meta.url)),
	'../lib/consent-manifest.generated.ts'
);
const source = await createStaticManifestModule({
	manifestURL: `${backendURL}/manifest`,
});
mkdirSync(dirname(target), { recursive: true });
writeFileSync(
	target,
	`// Generated by scripts/generate-manifest.ts\n${source}`
);
console.log(`[next-compat] wrote ${target} from ${backendURL}/manifest`);
