// Where `NativeC15tSpec` comes from when the bridge needs one to compile against.
//
// `NativeC15tSpec` is generated, and it is generated by whoever runs Codegen: in a React
// Native app that is the app build, which compiles the spec into its own module. A library
// compiled here cannot see that, so this module exists to give the bridge something to
// compile and unit-test against, and nothing more. It is wired as `compileOnly`, so the
// class is absent from the published AAR and the host app's copy is the only one at
// runtime. Two copies of that class in one APK is a duplicate-class failure, which is what
// this avoids -- and it is also why the generated output below stays inside this module:
// swapping the source set changes what compiles here, never what ships.
//
// `c15t.spec.source` chooses between the two things this module can compile:
//
// - `auto` and `stub`: the hand-written stand-in in `src/main/java`.
// - `codegen`: `src/specs/NativeC15t.ts` through `@react-native/codegen`, into
//   `build/generated/c15t-spec`. This is the repository running React Native's generator
//   against its own spec, which no build here did until that mode existed.
//
// `codegen` proves the bridge compiles against generated output. It cannot prove the
// stand-in still matches that output, because in this mode the stand-in is not compiled at
// all: `src/specs/__tests__/android-spec-surface.test.ts` owns that comparison, and CI runs
// both. `stub` says plainly that the stand-in is a stand-in, and is the mode the bridge's
// unit tests are written against.
//
// Standalone only. React Native never autolinks this module, so unlike the bridge it can
// apply plugins through the build.

plugins {
	id("com.android.library")
}

fun property(name: String): String? = findProperty(name)?.toString()?.takeIf { it.isNotBlank() }

val specSource = property("c15t.spec.source") ?: "auto"
require(specSource in setOf("auto", "stub", "codegen")) {
	"c15t-spec: c15t.spec.source=$specSource is not a source of NativeC15tSpec. Use auto or " +
		"stub for the hand-written stand-in in src/main/java, or codegen to generate the spec " +
		"from src/specs with @react-native/codegen."
}
val usesCodegen = specSource == "codegen"

/** The `@c15t/react-native` package root: it owns `package.json`, `src/specs`, `node_modules`. */
val packageRoot = rootDir.parentFile

/** The generator the drift check spawns too, so nothing is proved by a second implementation. */
val codegenScript = File(packageRoot, "android/codegen/generate-spec.mjs")

/**
 * Where `node` and the project Codegen reads `package.json` from.
 *
 * Read here rather than inside the task's configuration block: inside a `register { }`
 * closure Gradle's delegate owns property lookup, so the `property()` helper above is
 * shadowed by the task's own dynamic scope and an unknown project property throws as a
 * task property instead.
 */
val nodeExecutable = property("c15t.nodeExecutable") ?: "node"
val codegenProjectRoot = property("c15t.codegenProjectRoot")?.let(::file) ?: packageRoot

/** Codegen writes `java/` (the spec) and `jni/` (the C++ glue, which AGP never sees). */
val codegenOutputDir = layout.buildDirectory.dir("generated/c15t-spec")
val generatedJavaDir = codegenOutputDir.map { it.dir("java") }

android {
	namespace = "com.c15t.reactnative.spec"
	compileSdk = property("compileSdkVersion")?.toIntOrNull() ?: 36

	defaultConfig {
		minSdk = property("minSdkVersion")?.toIntOrNull() ?: 24
	}

	compileOptions {
		sourceCompatibility = JavaVersion.VERSION_17
		targetCompatibility = JavaVersion.VERSION_17
	}

	buildFeatures {
		buildConfig = false
	}
}

dependencies {
	// The generated spec carries `@DoNotStrip` and `@Nonnull` where the stand-in carries
	// `@Nullable`, and both annotations are compile-scope dependencies of `react-android`
	// itself, so the one coordinate covers either source. Nothing extra is declared here on
	// purpose: a version of React Native that stopped shipping one would fail this module
	// the same way it would fail the app build that generated the file.
	val reactNativeVersion = property("c15t.reactNativeVersion")
	compileOnly(
		if (reactNativeVersion == null) {
			"com.facebook.react:react-android"
		} else {
			"com.facebook.react:react-android:$reactNativeVersion"
		},
	)
}

if (usesCodegen) {
	/**
	 * Generate the spec.
	 *
	 * Plain paths, not `Provider`s, and a `dependsOn` on the compile tasks rather than a
	 * task-output relationship: AGP 9 rejects provider-backed source directories, and the
	 * generated `java/` directory has to exist as a path the moment the source set is read.
	 * A top-level `return` is not available in a `.gradle.kts` either, which is why the
	 * whole block is one `if` rather than an early exit.
	 */
	val generateC15tSpec = tasks.register("generateC15tSpec", Exec::class.java) {
		group = "build"
		description = "Generate NativeC15tSpec from src/specs with @react-native/codegen."

		inputs.dir(File(packageRoot, "src/specs"))
		inputs.file(File(packageRoot, "package.json"))
		inputs.file(codegenScript)
		outputs.dir(codegenOutputDir)

		val outputDirectory = codegenOutputDir.get().asFile.absolutePath

		commandLine(
			nodeExecutable,
			codegenScript.absolutePath,
			"--platform", "android",
			"--output", outputDirectory,
			"--project-root", codegenProjectRoot.absolutePath,
		)
	}

	// The swap: this module compiles the generated spec instead of the stand-in, and the
	// stand-in directory is gone from the source set rather than merely shadowed, so a
	// generated file the stand-in lacks cannot be silently satisfied by the hand-written one.
	//
	// Addressed through the `api.dsl` interface because AGP 9's implementation type for a
	// source set no longer implements the legacy `AndroidLibrarySourceSet` the `android {}`
	// accessor is typed against, and the cast is what fails, not the call. `directories`
	// rather than `setSrcDirs` because AGP 9.2 deprecates the latter.
	extensions.configure<com.android.build.api.dsl.LibraryExtension>("android") {
		sourceSets.getByName("main").java.directories.apply {
			clear()
			add(generatedJavaDir.get().asFile.absolutePath)
		}
	}

	// A plain path tells nobody who writes it, so the ordering is stated. `preBuild` is the
	// task AGP hangs the rest of the build behind, and it is what React Native's own plugin
	// uses for the same reason; the compile tasks are named too because AGP's annotation
	// extraction and lint tasks read the same source directories.
	tasks.named("preBuild").configure { dependsOn(generateC15tSpec) }

	tasks.withType(JavaCompile::class.java).configureEach { dependsOn(generateC15tSpec) }
}
