// A stand-in for the Codegen output, never shipped.
//
// `NativeC15tSpec` is generated, and it is generated by whoever runs Codegen: in a React
// Native app that is the app build, which emits it into its own ReactCodegen module. A library
// compiled here cannot see that, so this module exists to give the bridge something to compile
// and unit-test against, and nothing more. It is wired as `compileOnly`, so the class is absent
// from the published AAR and the host app's generated class is the only one at runtime. Two
// copies of that class in one APK is a duplicate-class failure, which is what this avoids.
//
// `c15t.spec.source=codegen` is not wired yet: no build script in this project runs RN's
// generator, so this source set is always the stand-in. That means nothing here proves the
// stand-in matches what Codegen emits for src/specs/NativeC15t.ts. The property is rejected
// below rather than silently ignored, so a green build can never be read as a Codegen check.
// Wiring that mode, and running it in CI, is open work.
//
// Standalone only. React Native never autolinks this module, so unlike the bridge it can apply
// plugins through the build.

plugins {
	id("com.android.library")
}

fun property(name: String): String? = findProperty(name)?.toString()?.takeIf { it.isNotBlank() }

// `codegen` would replace this source set with generated output. Nothing does, so honouring
// the value would report a Codegen pass that never asked Codegen anything.
val specSource = property("c15t.spec.source") ?: "auto"
require(specSource in setOf("auto", "stub")) {
    "c15t-spec: c15t.spec.source=$specSource is not implemented. Only auto and stub are " +
        "supported, and both compile the stand-in in this standalone build. Running RN's " +
        "Codegen against src/specs/NativeC15t.ts is not wired into any task yet."
}

android {
	namespace = "com.c15t.reactnative.spec"
	compileSdk = property("compileSdkVersion")?.toIntOrNull() ?: 36

	defaultConfig {
		minSdk = property("minSdkVersion")?.toIntOrNull() ?: 24
	}

	compileOptions {
		sourceCompatibility = JavaVersion.VERSION_17
		targetCompatibility = JavaVersion.VERSION_17
	}

	buildFeatures {
		buildConfig = false
	}
}

dependencies {
	val reactNativeVersion = property("c15t.reactNativeVersion")
	compileOnly(
		if (reactNativeVersion == null) {
			"com.facebook.react:react-android"
		} else {
			"com.facebook.react:react-android:$reactNativeVersion"
		},
	)
}
