// A stand-in for the Codegen output, never shipped.
//
// `NativeC15tSpec` is generated, and it is generated by whoever runs Codegen: in a React
// Native app that is the app build, which emits it into its own ReactCodegen module. A library
// compiled here cannot see that, so this module exists to give the bridge something to compile
// and unit-test against, and nothing more. It is wired as `compileOnly`, so the class is absent
// from the published AAR and the host app's generated class is the only one at runtime. Two
// copies of that class in one APK is a duplicate-class failure, which is what this avoids.
//
// Build with -Pc15t.spec.source=codegen to run the real Codegen instead, which is what CI
// should do: it replaces this source set with the generated output, and it is the check that
// the stand-in has not drifted.
//
// Standalone only. React Native never autolinks this module, so unlike the bridge it can apply
// plugins through the build.

plugins {
	id("com.android.library")
}

fun property(name: String): String? = findProperty(name)?.toString()?.takeIf { it.isNotBlank() }

android {
	namespace = "com.c15t.reactnative.spec"
	compileSdk = property("compileSdkVersion")?.toIntOrNull() ?: 36

	defaultConfig {
		minSdk = property("minSdkVersion")?.toIntOrNull() ?: 24
	}

	compileOptions {
		sourceCompatibility = JavaVersion.VERSION_17
		targetCompatibility = JavaVersion.VERSION_17
	}

	buildFeatures {
		buildConfig = false
	}
}

dependencies {
	val reactNativeVersion = property("c15t.reactNativeVersion")
	compileOnly(
		if (reactNativeVersion == null) {
			"com.facebook.react:react-android"
		} else {
			"com.facebook.react:react-android:$reactNativeVersion"
		},
	)
}
