# .github/workflows/check-pr-title.yml
name: "Check PR"

on:
  # Use pull_request_target to handle forks and allow commenting
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

# Permissions needed to post comments on the PR
permissions:
  pull-requests: write

jobs:
  validate-pr:
    name: PR title
    runs-on: ubuntu-latest
    steps:
      # Step 1: Lint the PR title
      - name: 🧐 Lint PR Title
        uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Default types match Conventional Commits: fix, feat, chore, build, ci, docs, perf, refactor, revert, style, test
        # You can customize types via 'types' input if needed

      # Step 2: Post error comment if linting failed
      - name: ✏️ Post Error Comment
        # Run only if the linting step failed (error_message is not null)
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          # Use a unique header to identify the comment for updates/deletion
          header: pr-title-lint-error
          # Provide a helpful error message with emojis
          message: |
            Hey there and thank you for opening this pull request! 👋🏼

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.
            Here is an example:
            ```
            <type>[optional scope]: <description>
            fix: I fixed something for consent.management
            ```

            Details:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      # Step 3: Update/Delete comment if linting passed
      - name: 🎉 Update/Delete Comment on Success
        # Run only if the linting step passed (error_message is null)
        if: steps.lint_pr_title.outputs.error_message == null
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          # Use the same header to find and update/delete the previous comment
          header: pr-title-lint-error
          # Provide a positive confirmation, effectively deleting the error message
          message: |
            Thank you for following the naming conventions for pull request titles! 🙏
