# 🚀 c15t production deployment workflow (Manual)
name: Deploy docs (Production)

on:
  # 📌 Manual trigger only for production deployments
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy (main or canary)'
        required: true
        type: choice
        options:
          - main
          - canary

permissions:
  contents: read
  issues: write
  pull-requests: write
  deployments: write

jobs:
  deploy:
    concurrency:
      group: docs-production-${{ github.event.inputs.branch }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      # 📦 Setup pnpm (used by docs template/scripts)
      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: ♻️ Setup pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 📥 Install workspace deps
        run: pnpm install --frozen-lockfile

      - name: ▲ C15T Production Deployment
        id: c15t
        uses: ./internals/c15t-github-action
        with:
          # Auth
          GITHUB_TOKEN: ${{ github.token }}
          github_app_id: ${{ secrets.CONSENT_APP_ID }}
          github_app_private_key: ${{ secrets.CONSENT_APP_PRIVATE_KEY }}
          github_app_installation_id: 81013186

          # Production target
          target: production

          # Comment behavior
          header: c15t-docs-production
          append: "true"
          hide_details: "true"

          # Vercel
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}

          assign_alias_on_branch: ${{ github.event.inputs.branch }}
          alias_domains: |
            ${{ github.event.inputs.branch == 'canary' && 'canary.c15t.com' || 'c15t.com' }}

          # Branch deployment policies
          deploy_on_push_branches: ${{ github.event.inputs.branch }}

          # Orchestration & gating
          consent_git_token: ${{ secrets.CONSENT_GIT_TOKEN }}
          only_if_changed: "false"
          change_globs: |
            docs/**
            packages/*/src/**
            packages/*/package.json
          check_template_changes: "true"
