name: Sync Canary with Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    name: Sync Canary with Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Sync Canary with Main
        run: |
          # Check if canary branch exists
          if git ls-remote --heads origin canary | grep canary; then
            # Create or update canary branch
            git checkout -B canary
            git pull origin main
            git push origin canary --force
          else
            # Create canary branch if it doesn't exist
            git checkout -b canary
            git push origin canary
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 