name: Test Custom Sticky Comment Action

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find PR for this branch
        id: find_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            let prNumber = context.payload?.pull_request?.number || '';
            if (!prNumber && context.eventName !== 'pull_request') {
              const ref = context.ref || '';
              const branch = ref.startsWith('refs/heads/') ? ref.replace('refs/heads/', '') : ref;
              const { data: prs } = await github.rest.pulls.list({
                owner,
                repo,
                state: 'open',
                head: `${owner}:${branch}`,
                per_page: 1,
              });
              if (prs.length) {
                prNumber = String(prs[0].number);
              }
            }
            core.setOutput('pr_number', prNumber);

      - name: Generate GitHub App token
        id: app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CONSENT_APP_ID }}
          private-key: ${{ secrets.CONSENT_APP_PRIVATE_KEY }}

      - name: Post sticky test comment
        if: ${{ steps.find_pr.outputs.pr_number != '' }}
        uses: ./internals/c15t-github-action
        with:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
          author_login: consent-io
          header: "[test]"
          number: ${{ steps.find_pr.outputs.pr_number }}
          append: "true"
          skip_unchanged: "false"
          message: |
            ✅ Test run for custom action
            run_id: ${{ github.run_id }}
            sha: ${{ github.sha }}
            actor: ${{ github.actor }}