name: Full validation

on:
  schedule:
    - cron: '17 2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  checks:
    permissions:
      contents: read
      actions: read
      id-token: write
    uses: ./.github/workflows/ci.yml
