import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import {
	ConsentManagerDialog,
	ConsentManagerProvider,
	CookieBanner,
} from '@c15t/nextjs';
import type { ReactNode } from 'react';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ConsentManagerProvider
					options={{
						mode: 'offline', // For development purposes - no requests are sent to the backend
						// mode: 'c15t',
						// backendURL: 'your-instance-url',
						react: {
							colorScheme: 'dark', // Hard coded to dark for this example, relies on .dark classname for automatic
						},
					}}
				>
					<CookieBanner />
					<ConsentManagerDialog />
					{children}
				</ConsentManagerProvider>
			</body>
		</html>
	);
}
